### ISSUE TITLE
Roadmap & Feature Requests

### ISSUE THREAD

**Issue by RandomLegoBrick** [Bobertism/Bobertism#1]
Features:

- [ ] Buttons on tiles to copy large/small image
- [ ] Popup for tiles that let the user view details
- [ ] Download buttons
- [ ] Light/Dark theme
- [ ] Better tile css
- [ ] About page (?)
- [ ] Home page with list of new bobert arivals (?)
- [ ] Header & nav bar (?)

Boberts:

- [ ] Bobert Think
- [x] Bobert Chad
- [ ] Bobert child (bobit?)
- [x] Surprised Bobert

Post feature requests below :point_down:
